runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css
  secure: always
  
- url: /adventurers
  script: /collections/adventurers.php
  
- url: /
  script: index.php
  secure: always
