runtime: php72
#api_version: 1
#threadsafe: true

env_variables:

  MYSQL_DSN: mysql:unix_socket=/cloudsql/manasmith-221002:us-east1:manasmith;dbname=collections
  MYSQL_USER: silke
  MYSQL_PASSWORD: Y1j5]NZb)GfH

handlers:

- url: /static
  static_dir: public
  
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
