runtime: php55
api_version: 1
threadsafe: true

env_variables:

  MYSQL_DSN: mysql:unix_socket=/cloudsql/manasmith-221002:us-east1:manasmith;dbname=collections
  MYSQL_USER: silke
  MYSQL_PASSWORD: Y1j5]NZb)GfH

handlers:

- url: /css
  secure: always
  static_dir: css
  
- url: /scripts
  secure: always
  static_dir: scripts
  
- url: /adventurers
  secure: always
  script: /collections/adventurers.php
  
- url: /mana-circles
  secure: always
  script: /collections/mana-circles.php
  
- url: /dragons
  secure: always
  script: /collections/dragons.php
  
- url: /weapons
  secure: always
  script: /collections/weapons.php
  
- url: /wyrmprints
  secure: always
  script: /collections/wyrmprints.php
  
- url: /
  secure: always
  script: index.php
