runtime: php55
api_version: 1

handlers:

# CSS folder
- url: /css
  static_dir: css
  secure: always
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
  secure: always

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  secure: always

# Homepage
- url: /
  script: index.php
  secure: always
