runtime: php55
api_version: 1

handlers:

# Admin
- url: /admin
  script: /admin/index.php

# Homepage
- url: /
  script: index.php

# CSS folder
- url: /css
  static_dir: css
  
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
