runtime: php55
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: css
  secure: always
  
- url: /adventurers
  script: /collections/adventurers.php
  
- url: /mana-circles
  script: /collections/mana-circles.php
  
- url: /dragons
  script: /collections/dragons.php
  
- url: /weapons
  script: /collections/weapons.php
  
- url: /wyrmprints
  script: /collections/wyrmprints.php
  
- url: /
  script: index.php
  secure: always
