runtime: php55
api_version: 1
threadsafe: true
basic_scaling:
  max_instances: 10
  idle_timeout: 10m

handlers:

- url: /css
  static_dir: css
  secure: always
  
- url: /
  script: index.php
  secure: always
