runtime: php55
api_version: 1
threadsafe: true

env_variables:

  MYSQL_DSN: mysql:unix_socket=/cloudsql/manasmith-221002:us-east1:manasmith;dbname=collections
  MYSQL_USER: silke
  MYSQL_PASSWORD: Y1j5]NZb)GfH

handlers:

# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts.
- url: /(.+\.php)$
  script: \1
  
- url: /css
  secure: always
  static_dir: css
  
- url: /scripts
  secure: always
  static_dir: scripts
  
- url: /
  secure: always
  script: index.php
